/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package app.frames;

import app.models.Funcion;
import app.models.Sala;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.awt.event.WindowListener;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JFrame;

/**
 *
 * @author Juan José Molano Franco
 */
public class FrameGestionSala extends javax.swing.JFrame {

    private int seleccion = -1;  // Valor default, preferiblemente un número negativo
    private Funcion funcionSeleccionada = null;  // Función a gestionar

    /**
     * Creates new form FrameGestionSala
     */
    public FrameGestionSala(Sala sala) {
        initComponents();
        setLocationRelativeTo(null);
        // Esto se hace para poder detectar cuando la ventana se cierra con un listener
        setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
        // Aquí se hace el setup thel windowlistener
        AgregarWindowListener();
        llenarCombobox(sala);
        labelSala.setText("Gestionando sala " + sala.getId());
        labelAsientos.setText("Asientos totales: " + sala.getAsientos());
        labelFunciones.setText("Funciones programadas: " + sala.getFunciones().size());
    }
    
    private void llenarCombobox(Sala sala) {
        DefaultComboBoxModel model = new DefaultComboBoxModel();
        List<Funcion> funciones = sala.getFunciones();
        for (Funcion f : funciones) {
            model.addElement(f);
        }
        cbFunciones.setModel(model);
        try {
            cbFunciones.setSelectedIndex(0);
        } catch (Exception e) {
            model.addElement("NO HAY FUNCIONES");
        }
    }
    
    public int getSeleccion() {
        return seleccion;
    }
    
    public Funcion getFuncionSeleccionada() {
        return funcionSeleccionada;
    }
    
    private void AgregarWindowListener() {
        WindowListener exitListener = new WindowAdapter() {

            @Override
            public void windowClosing(WindowEvent e) {
                seleccion = 0;  // Marca que se cerró la ventana
            }
        };
        addWindowListener(exitListener);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelSala = new javax.swing.JLabel();
        labelAsientos = new javax.swing.JLabel();
        labelFunciones = new javax.swing.JLabel();
        botonVolver = new javax.swing.JButton();
        botonBorrarSala = new javax.swing.JButton();
        botonNuevaFuncion = new javax.swing.JButton();
        cbFunciones = new javax.swing.JComboBox<>();
        botonGestionarFuncion = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        labelSala.setText("Gestionando sala n");

        labelAsientos.setText("Asientos totales: x");

        labelFunciones.setText("Funciones programadas: x");

        botonVolver.setText("Volver");
        botonVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonVolverActionPerformed(evt);
            }
        });

        botonBorrarSala.setText("Borrar sala");
        botonBorrarSala.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBorrarSalaActionPerformed(evt);
            }
        });

        botonNuevaFuncion.setText("Nueva función");
        botonNuevaFuncion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonNuevaFuncionActionPerformed(evt);
            }
        });

        cbFunciones.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        botonGestionarFuncion.setText("Gestionar funcion");
        botonGestionarFuncion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonGestionarFuncionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 28, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(botonVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(botonBorrarSala, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(botonNuevaFuncion))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(cbFunciones, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(botonGestionarFuncion)
                                .addGap(46, 46, 46)))
                        .addGap(24, 24, 24))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelSala)
                                    .addComponent(labelAsientos)))
                            .addComponent(labelFunciones))
                        .addGap(129, 129, 129))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(62, Short.MAX_VALUE)
                .addComponent(labelSala)
                .addGap(18, 18, 18)
                .addComponent(labelAsientos)
                .addGap(18, 18, 18)
                .addComponent(labelFunciones)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonVolver)
                    .addComponent(botonBorrarSala)
                    .addComponent(botonNuevaFuncion))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbFunciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonGestionarFuncion))
                .addGap(40, 40, 40))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonVolverActionPerformed
        seleccion = 1;
    }//GEN-LAST:event_botonVolverActionPerformed

    private void botonBorrarSalaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBorrarSalaActionPerformed
        seleccion = 2;
    }//GEN-LAST:event_botonBorrarSalaActionPerformed

    private void botonNuevaFuncionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonNuevaFuncionActionPerformed
        seleccion = 3;
    }//GEN-LAST:event_botonNuevaFuncionActionPerformed

    private void botonGestionarFuncionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonGestionarFuncionActionPerformed
        seleccion = 4;
        Object objSeleccionado = cbFunciones.getSelectedItem();
        if (! (objSeleccionado instanceof String)) {
            funcionSeleccionada = (Funcion) objSeleccionado;
        }
    }//GEN-LAST:event_botonGestionarFuncionActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonBorrarSala;
    private javax.swing.JButton botonGestionarFuncion;
    private javax.swing.JButton botonNuevaFuncion;
    private javax.swing.JButton botonVolver;
    private javax.swing.JComboBox<String> cbFunciones;
    private javax.swing.JLabel labelAsientos;
    private javax.swing.JLabel labelFunciones;
    private javax.swing.JLabel labelSala;
    // End of variables declaration//GEN-END:variables
}
