/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package app.frames;

import app.models.Funcion;
import app.models.Sala;
import app.models.Usuario;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.awt.event.WindowListener;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author johan
 */
public class FrameVerFuncionesUsuario extends javax.swing.JFrame {

    /**
     * Creates new form FrameVerFuncionesUsuario
     */
    private int seleccion = -1;
    private Usuario usuario;
    private List<Sala> salas;

    /**
     * Creates new form FrameUsuario
     */
    public FrameVerFuncionesUsuario(Usuario usuario, List<Sala> salas) {
        this.salas = salas;
        this.usuario = usuario;
        initComponents();
        setLocationRelativeTo(null);
        // Esto se hace para poder detectar cuando la ventana se cierra con un listener
        setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
        // Aquí se hace el setup del windowListener
        AgregarWindowListener();
        llenarTabla();
        actionListenerTablaFunciones();
    }

    public int getSeleccion() {
        return seleccion;
    }

    public void AgregarWindowListener() {
        WindowListener exitListener = new WindowAdapter() {

            @Override
            public void windowClosing(WindowEvent e) {
                seleccion = 0;  // Marca que se cerró la ventana
            }
        };
        addWindowListener(exitListener);
    }

    public void llenarTabla() {
        DefaultTableModel model = new DefaultTableModel() {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false; // Make all cells non-editable
            }
        };

        model.setColumnIdentifiers(new Object[]{"ID", "Titulo", "Asientos", "Hora inicio", "Hora fin"});

        if (salas == null || salas.isEmpty()) {
            funcionesTable.setModel(model);
            return;
        }

        try {
            for (Sala sala : salas) {
                if (sala == null || sala.getFunciones() == null || sala.getFunciones().isEmpty()) {
                    continue; // Saltar si no hay funciones
                }

                for (Funcion funcion : sala.getFunciones()) {
                    if (funcion == null) {
                        continue; // Precaución extra
                    }
                    model.addRow(new Object[]{
                        funcion.getId(),
                        funcion.getTitulo(),
                        funcion.getAsientos().length,
                        funcion.getInicio(),
                        funcion.getFin()
                    });
                }
            }
        } catch (Exception e) {
            System.err.println("Error al llenar la tabla de funciones: " + e.getMessage());
            e.printStackTrace();
        }

        funcionesTable.setModel(model);
    }

    private void actionListenerTablaFunciones() {
        funcionesTable.getSelectionModel().addListSelectionListener(e -> {
            if (!e.getValueIsAdjusting() && funcionesTable.getSelectedRow() != -1) {
                int selectedRow = funcionesTable.getSelectedRow();

                idLabel.setText(funcionesTable.getValueAt(selectedRow, 0).toString());
                tituloLabel.setText(funcionesTable.getValueAt(selectedRow, 1).toString());
                funcionesTable.clearSelection();
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        funcionesTable = new javax.swing.JTable();
        regresarBtn = new javax.swing.JButton();
        comprarBtn = new javax.swing.JButton();
        funcionLabel = new javax.swing.JLabel();
        tituloLabelNONEDITABLE = new javax.swing.JLabel();
        idLabelNONEDITABLE = new javax.swing.JLabel();
        idLabel = new javax.swing.JLabel();
        tituloLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        funcionesTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Titulo", "Asientos", "Hora inicio", "Hora fin"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        funcionesTable.setToolTipText("");
        jScrollPane1.setViewportView(funcionesTable);

        regresarBtn.setText("Regresar");
        regresarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regresarBtnActionPerformed(evt);
            }
        });

        comprarBtn.setText("Comprar ticket");
        comprarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comprarBtnActionPerformed(evt);
            }
        });

        funcionLabel.setText("Funcion seleccionada:");

        tituloLabelNONEDITABLE.setText("Titulo:");

        idLabelNONEDITABLE.setText("ID:");

        idLabel.setText("     ");

        tituloLabel.setText("     ");
        tituloLabel.setToolTipText("");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(funcionLabel)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(idLabelNONEDITABLE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(idLabel)
                                .addGap(67, 67, 67)
                                .addComponent(tituloLabelNONEDITABLE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tituloLabel)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 107, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(comprarBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(regresarBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comprarBtn)
                    .addComponent(funcionLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(regresarBtn)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tituloLabelNONEDITABLE)
                        .addComponent(idLabelNONEDITABLE)
                        .addComponent(idLabel)
                        .addComponent(tituloLabel)))
                .addGap(15, 15, 15))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void comprarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comprarBtnActionPerformed
        // TODO add your handling code here:
        seleccion = 2;
    }//GEN-LAST:event_comprarBtnActionPerformed

    private void regresarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regresarBtnActionPerformed
        // TODO add your handling code here:
        seleccion = 1;
    }//GEN-LAST:event_regresarBtnActionPerformed

    public int getFuncionId() {
        try {
        return Integer.parseInt(idLabel.getText());
        } catch (NumberFormatException e) {
            return -1;
        }
    }
    
    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton comprarBtn;
    private javax.swing.JLabel funcionLabel;
    private javax.swing.JTable funcionesTable;
    private javax.swing.JLabel idLabel;
    private javax.swing.JLabel idLabelNONEDITABLE;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton regresarBtn;
    private javax.swing.JLabel tituloLabel;
    private javax.swing.JLabel tituloLabelNONEDITABLE;
    // End of variables declaration//GEN-END:variables
}
